version: 2.1 # use CircleCI 2.1
commands:
  test_all:
    description: "restore cache based on yarn.lock and install dependencies"
    steps:
      - checkout
      - run: mkdir -p ~/junit
      - run: echo "$(md5sum package.json yarn.lock) $(node --version) $(yarn --version)" > .dependencychecksum
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum ".dependencychecksum" }}
      - restore_cache:
          # Restore branch-specific cache if it exists
          key: dependency-cache-{{ .Branch }}-{{ checksum ".dependencychecksum" }}
      - run: yarn --frozen-lockfile
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum ".dependencychecksum" }}
          paths:
            - ./node_modules
      - save_cache: # special step to save the dependency cache for branch-specific version
          key: dependency-cache-{{ .Branch }}-{{ checksum ".dependencychecksum" }}
          paths:
            - ./node_modules
      - run:
          command: yarn test
          environment:
            MOCHA_FILE: ~/junit/test-results.xml
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

jobs: &jobs
  test:
    parameters:
      node_version:
        type: 'string'
    docker:
      - image: circleci/node:<< parameters.node_version >>
    steps:
      - test_all
workflows:
  # version: 2
    build-and-test:
      jobs:
        - test:
            node_version: "10"
        - test:
            node_version: "12"
        - test:
            node_version: "14"
